apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poseidon.fullname" . }}
  labels:
    {{- include "poseidon.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Release.IsUpgrade }}
  {{- if  .Values.airbyteConfigs.webhookId }}
  AIRBYTE_WEBHOOK_ID: {{ .Values.airbyteConfigs.webhookId | quote }}
  {{- else }}
  AIRBYTE_WEBHOOK_ID: {{ randAlphaNum 64 | quote }}
  {{- end }}
  FAROS_STATIC_API_KEY_ID: {{ uuidv4 | quote }}
  FAROS_STATIC_API_KEY: {{ randAlphaNum 32 | quote }}
{{- else }}
  {{- $fullName := include "poseidon.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
  {{- if  .Values.airbyteConfigs.webhookId }}
  AIRBYTE_WEBHOOK_ID: {{ .Values.airbyteConfigs.webhookId | quote }}
  {{- else }}
  AIRBYTE_WEBHOOK_ID: {{ $secret.data.AIRBYTE_WEBHOOK_ID | b64dec | quote }}
  {{- end }}
  FAROS_STATIC_API_KEY_ID: {{ $secret.data.FAROS_STATIC_API_KEY_ID | b64dec | quote }}
  FAROS_STATIC_API_KEY: {{ $secret.data.FAROS_STATIC_API_KEY | b64dec | quote }}
{{- end }}
  {{ if .Values.global.airbyte.enabled }}
  AIRBYTE_PASSWORD: {{ .Values.airbyteConfigs.password | quote }}
  {{- end }}
  FAROS_ROOT_USER: {{ .Values.global.faros.rootUser | quote }}
  SEGMENT_ANALYTICS_KEY: ""
  GOOGLE_MAPS_API_KEY: {{ required "global.poseidon.googleMapsAPIKey value is empty or not defined" .Values.global.poseidon.googleMapsAPIKey | quote }}
  REDIS_STUNNEL_PASSWORD: NOT_DEFINED
{{- if and .Values.stsJwt.privateKeyFile .Values.stsJwt.publicKeyFile }}
  STS_JWT_PRIVATE_KEY: |-
{{ .Files.Get .Values.stsJwt.privateKeyFile | indent 4 }}
  STS_JWT_PUBLIC_KEY: |-
{{ .Files.Get .Values.stsJwt.publicKeyFile | indent 4 }}
{{- else }}
  STS_JWT_PRIVATE_KEY: {{ required ".Values.stsJwt.privateKey value is empty or not defined" .Values.stsJwt.privateKey | quote }}
  STS_JWT_PUBLIC_KEY: {{ required ".Values.stsJwt.publicKey value is empty or not defined" .Values.stsJwt.publicKey | quote }}
{{- end }}
{{- if and .Values.global.poseidon.vaultUri .Values.global.poseidon.vaultToken }}
  SECRETS_VAULT_URI: {{ .Values.global.poseidon.vaultUri }}
  SECRETS_VAULT_TOKEN: {{ .Values.global.poseidon.vaultToken }}
{{- end }}
{{- if .Values.global.poseidon.vaultExtraHeaders }}
  SECRETS_VAULT_EXTRA_HEADERS: {{ .Values.global.poseidon.vaultExtraHeaders | quote }}
{{- end }}

  {{- $dbHost := .Values.externalDb.host }}
  {{- $dbPort := .Values.externalDb.port }}
  {{- $dbName := .Values.externalDb.database }}
  {{- $dbUsername := .Values.externalDb.username }}
  {{- $dbPassword := .Values.externalDb.password }}
  {{- if .Values.poseidonDb.enabled }}
    {{- $dbHost = printf "%s-%s.%s.svc" .Release.Name .Values.dbName .Release.Namespace }}
    {{- $dbPort = .Values.global.postgresql.service.ports.postgresql }}
    {{- $dbName = .Values.poseidonDb.auth.database }}
    {{- $dbUsername = .Values.poseidonDb.auth.username }}
    {{- $dbPassword = .Values.poseidonDb.auth.password }}
  {{- end }}
  DATABASE_URL: "jdbc:postgresql://{{ $dbHost }}:{{ $dbPort }}/{{ $dbName }}"
  DATABASE_USERNAME: {{ $dbUsername }}
  DATABASE_PASSWORD: {{ $dbPassword | quote }}
