apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iris.fullname" . }}
  labels:
    {{- include "iris.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $dbHost := .Values.externalDb.host }}
  {{- $dbPort := .Values.externalDb.port }}
  {{- $dbName := .Values.externalDb.database }}
  {{- $dbUsername := .Values.externalDb.username }}
  {{- $dbPassword := .Values.externalDb.password }}
{{- if and .Values.externalDb.passwordSecret.namespace .Values.externalDb.passwordSecret.name .Values.externalDb.passwordSecret.key }}
  {{- $secret := lookup "v1" "Secret" .Values.externalDb.passwordSecret.namespace .Values.externalDb.passwordSecret.name }}
  {{- $dbPassword = index $secret.data .Values.externalDb.passwordSecret.key | b64dec }}
{{- end }}
  {{- if .Values.irisDb.enabled }}
    {{- $dbHost = printf "%s-%s.%s.svc" .Release.Name .Values.dbName .Release.Namespace }}
    {{- $dbPort = .Values.global.postgresql.service.ports.postgresql }}
    {{- $dbName = .Values.irisDb.auth.database }}
    {{- $dbUsername = .Values.irisDb.auth.username }}
    {{- $dbPassword = .Values.irisDb.auth.password }}
  {{- end }}
  IRIS_DB_HOST: {{ $dbHost | quote }}
  IRIS_DB_PORT: {{ $dbPort | quote }}
  IRIS_DB_NAME: {{ $dbName | quote }}
  IRIS_DB_USER: {{ $dbUsername | quote }}
  IRIS_DB_PASSWORD: {{ $dbPassword | quote }}
