apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
data:
  HASURA_URL: "http://{{ include "hasura.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}"
