apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alastor.fullname" . }}
  labels:
    {{- include "alastor.labels" . | nindent 4 }}
data:
{{- $basePath := .Values.basePath }}

  ALASTOR_PORT: {{ .Values.service.targetPort | quote }}
  BASE_PATH: "{{ $basePath }}"
  DISABLE_ESLINT_PLUGIN: "true"
  ENABLE_API_PROXY_LOGGING: "false"
  FAROS_STATIC_SESSION_TTL_SECONDS: "172800"
  FAROS_STATIC_ALLOW_INSECURE_COOKIES: "true"
  LOG_LEVEL: "debug"
  NEXTAUTH_URL: "{{ .Values.global.faros.appUri }}{{ $basePath }}/api/auth"
  NEXT_PUBLIC_FAROS_API_DOCUMENTATION: "https://docs.faros.ai/"
  NEXT_PUBLIC_FAROS_REPORTS_COLLECTION_ID: "2"
  NEXT_PUBLIC_UNLEASH_APP_NAME: "alastor"
  NEXT_PUBLIC_ENABLE_GRAPHQL_V2: "true"
  NODE_ENV: "production"
  FAROS_NODE_OPTIONS: "--heapsnapshot-signal=SIGUSR2 --max-old-space-size=1024 {{ include "faros-ai.farosNodeOptions" . }}"
{{- if .Values.global.alastor.nextPublicWorkflowsApUrl }}
  NEXT_PUBLIC_WORKFLOWS_AP_URL: {{ .Values.global.alastor.nextPublicWorkflowsApUrl | quote }}
{{- end }}
