apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alastor.fullname" . }}
  labels:
    {{- include "alastor.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Release.IsUpgrade }}
  FAROS_STATIC_SESSION_SECRET: {{ randAlphaNum 20 }}
  UNLEASH_PROXY_SECRETS: {{ randAlphaNum 20 }}
{{- else }}
  {{- $fullName := include "alastor.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
  FAROS_STATIC_SESSION_SECRET: {{ $secret.data.FAROS_STATIC_SESSION_SECRET | b64dec | quote }}
  UNLEASH_PROXY_SECRETS: {{ $secret.data.UNLEASH_PROXY_SECRETS | b64dec | quote }}
{{- end }}
{{- if and .Values.global.alastor.nextAuthProvidersSecret.namespace .Values.global.alastor.nextAuthProvidersSecret.name .Values.global.alastor.nextAuthProvidersSecret.key }}
  {{- $secret := lookup "v1" "Secret" .Values.global.alastor.nextAuthProvidersSecret.namespace .Values.global.alastor.nextAuthProvidersSecret.name }}
  NEXTAUTH_PROVIDERS: {{ index $secret.data .Values.global.alastor.nextAuthProvidersSecret.key | b64dec }}
{{- else }}
  NEXTAUTH_PROVIDERS: {{ required "global.alastor.nextAuthProviders value is empty or not defined" .Values.global.alastor.nextAuthProviders | quote }}
{{- end }}
{{- if and .Values.global.alastor.nextPublicFarosStaticLicenseSecret.namespace .Values.global.alastor.nextPublicFarosStaticLicenseSecret.name .Values.global.alastor.nextPublicFarosStaticLicenseSecret.key }}
  {{- $secret := lookup "v1" "Secret" .Values.global.alastor.nextPublicFarosStaticLicenseSecret.namespace .Values.global.alastor.nextPublicFarosStaticLicenseSecret.name }}
  NEXT_PUBLIC_FAROS_STATIC_LICENSE: {{ index $secret.data .Values.global.alastor.nextPublicFarosStaticLicenseSecret.key | b64dec }}
{{- else }}
  NEXT_PUBLIC_FAROS_STATIC_LICENSE: {{ required "global.alastor.nextPublicFarosStaticLicense value is empty or not defined" .Values.global.alastor.nextPublicFarosStaticLicense | quote }}
{{- end }}
{{- if and .Values.global.alastor.workflowsApSigningKeyId .Values.global.alastor.workflowsApSigningKey }}
  WORKFLOWS_AP_SIGNING_KEY_ID: {{ .Values.global.alastor.workflowsApSigningKeyId | quote }}
  WORKFLOWS_AP_SIGNING_KEY: {{ .Values.global.alastor.workflowsApSigningKey | quote }}
{{- end }}
