apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alastor.fullname" . }}
  labels:
    {{- include "alastor.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Release.IsUpgrade }}
  FAROS_STATIC_SESSION_SECRET: {{ randAlphaNum 20 }}
  UNLEASH_PROXY_SECRETS: {{ randAlphaNum 20 }}
{{- else }}
  {{- $fullName := include "alastor.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
  FAROS_STATIC_SESSION_SECRET: {{ $secret.data.FAROS_STATIC_SESSION_SECRET | b64dec | quote }}
  UNLEASH_PROXY_SECRETS: {{ $secret.data.UNLEASH_PROXY_SECRETS | b64dec | quote }}
{{- end }}
  NEXTAUTH_PROVIDERS: {{ required "global.alastor.nextAuthProviders value is empty or not defined" .Values.global.alastor.nextAuthProviders | quote }}
  NEXT_PUBLIC_FAROS_STATIC_LICENSE: {{ required "global.alastor.nextPublicFarosStaticLicense value is empty or not defined" .Values.global.alastor.nextPublicFarosStaticLicense | quote }}
