apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aionapi.fullname" . }}
  labels:
    {{- include "aionapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aionapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configmap-v: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        secrets-v: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aionapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aionapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: AION_RELEASE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-aionworker
                  key: AION_RELEASE_BUCKET
            - name: AION_RELEASE_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-aionworker
                  key: AION_RELEASE_REGISTRY
            - name: AION_RELEASE_VERSION_FILE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-aionworker
                  key: AION_RELEASE_VERSION_FILE
            - name: FAROS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-poseidon
                  key: FAROS_API_URL
            - name: METABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-aionmetabase
                  key: METABASE_URL
            - name: METABASE_EMBEDDING_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-aionmetabase
                  key: MB_EMBEDDING_SECRET_KEY
            - name: METABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-aionmetabase
                  key: MB_JWT_SHARED_SECRET
            {{- include "aionv2.datadog.baseEnvVars" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "aionapi.fullname" . }}
            - secretRef:
                name: {{ include "aionapi.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: 1 # Must be 1 for liveness and startup probes per k8s docs
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: 2
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: efs-aion
              mountPath: /aion
            - name: efs-metabase
              mountPath: /metabase
              readOnly: true
      volumes:
        - name: efs-aion
          persistentVolumeClaim:
            claimName: efs-aion
        - name: efs-metabase
          persistentVolumeClaim:
            claimName: efs-metabase
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
