apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aionapi.fullname" . }}
  labels:
    {{- include "aionapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $dbHost := .Values.externalDb.host }}
  {{- $dbPort := .Values.externalDb.port }}
  {{- $dbName := .Values.externalDb.database }}
  {{- $dbUsername := .Values.externalDb.username }}
  {{- $dbPassword := .Values.externalDb.password }}
{{- if and .Values.externalDb.passwordSecret.namespace .Values.externalDb.passwordSecret.name .Values.externalDb.passwordSecret.key }}
  {{- $secret := lookup "v1" "Secret" .Values.externalDb.passwordSecret.namespace .Values.externalDb.passwordSecret.name }}
  {{- $dbPassword = index $secret.data .Values.externalDb.passwordSecret.key | b64dec }}
{{- end }}
  {{- if .Values.aionServiceDb.enabled }}
    {{- $dbHost = printf "%s-%s.%s.svc" .Release.Name .Values.dbName .Release.Namespace }}
    {{- $dbPort = .Values.global.postgresql.service.ports.postgresql }}
    {{- $dbName = .Values.aionServiceDb.auth.database }}
    {{- $dbUsername = .Values.aionServiceDb.auth.username }}
    {{- $dbPassword = .Values.aionServiceDb.auth.password }}
  {{- end }}
  AION_DATABASE_URL: "postgres://{{ $dbUsername }}:{{ $dbPassword }}@{{ $dbHost }}:{{ $dbPort }}/{{ $dbName }}"
  METABASE_ADMIN_USERNAME: {{ .Values.global.metabase.user }}
  {{- $fullName := include "aionapi.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
  # if not upgrading (module was not installed before), generate a random password
{{- if $secret }}
  METABASE_ADMIN_PASSWORD: {{ $secret.data.METABASE_ADMIN_PASSWORD | b64dec | quote }}
  {{- else }}
  METABASE_ADMIN_PASSWORD: {{ randAlphaNum 64 | quote }}
{{- end }}
{{- if and .Values.global.datadog.apiKey .Values.global.datadog.appKey }}
  DD_API_KEY: {{ .Values.global.datadog.apiKey | quote }}
  DD_APP_KEY: {{ .Values.global.datadog.appKey | quote }}
  DD_URL: {{ .Values.global.datadog.url | quote }}
{{- end }}
