apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aionmetabase.fullname" . }}
  labels:
    {{- include "aionmetabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $fullName := include "aionmetabase.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
{{- if not $secret }}
  # The MB_ENCRYPTION_SECRET_KEY random string should be base64 encoded. 
  MB_ENCRYPTION_SECRET_KEY: {{ randAlphaNum 64 | b64enc }}
  MB_EMBEDDING_SECRET_KEY: {{ randAlphaNum 64 }}
  MB_JWT_SHARED_SECRET: {{ randAlphaNum 64 | quote }}
  MB_API_KEY: {{ randAlphaNum 64 | sha256sum }}
  MB_PREMIUM_EMBEDDING_TOKEN: {{ randAlphaNum 64 | sha256sum }}
{{- else }}
  MB_ENCRYPTION_SECRET_KEY: {{ $secret.data.MB_ENCRYPTION_SECRET_KEY | b64dec | quote }}
  MB_EMBEDDING_SECRET_KEY: {{ $secret.data.MB_EMBEDDING_SECRET_KEY | b64dec | quote }}
  MB_JWT_SHARED_SECRET: {{ $secret.data.MB_JWT_SHARED_SECRET | b64dec | quote }}
  MB_API_KEY: {{ $secret.data.MB_API_KEY | b64dec | quote }}
  MB_PREMIUM_EMBEDDING_TOKEN: {{ $secret.data.MB_PREMIUM_EMBEDDING_TOKEN | b64dec | quote }}
{{- end }}
  # Variables for Metabase DB
  {{- $mbDbHost := .Values.externalDb.host }}
  {{- $mbDbPort := .Values.externalDb.port }}
  {{- $mbDbName := .Values.externalDb.database }}
  {{- $mbDbUsername := .Values.externalDb.username }}
  {{- $mbDbPassword := .Values.externalDb.password }}
  {{- if .Values.metabaseDb.enabled }}
    {{- $mbDbHost = printf "%s-%s.%s.svc" .Release.Name .Values.dbName .Release.Namespace }}
    {{- $mbDbPort = .Values.global.postgresql.service.ports.postgresql }}
    {{- $mbDbName = .Values.metabaseDb.auth.database }}
    {{- $mbDbUsername = .Values.metabaseDb.auth.username }}
    {{- $mbDbPassword = .Values.metabaseDb.auth.password }}
  {{- end }}

  MB_DB_CONNECTION_URI: "postgres://{{ $mbDbUsername }}:{{ $mbDbPassword }}@{{ $mbDbHost }}:{{ $mbDbPort }}/{{ $mbDbName }}"
