apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unleash.fullname" . }}
  labels:
    {{- include "unleash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $dbUser := .Values.externalDb.username }}
  {{- $dbUserPassword := .Values.externalDb.password }}
{{- if and .Values.externalDb.passwordSecret.namespace .Values.externalDb.passwordSecret.name .Values.externalDb.passwordSecret.key }}
  {{- $secret := lookup "v1" "Secret" .Values.externalDb.passwordSecret.namespace .Values.externalDb.passwordSecret.name }}
  {{- $dbUserPassword = index $secret.data .Values.externalDb.passwordSecret.key | b64dec }}
{{- end }}
  {{- $dbSuperUser := .Values.externalDb.superusername }}
  {{- $dbSuperUserPassword := .Values.externalDb.superuserpassword }}
{{- if and .Values.externalDb.superUserPasswordSecret.namespace .Values.externalDb.superUserPasswordSecret.name .Values.externalDb.superUserPasswordSecret.key }}
  {{- $secret := lookup "v1" "Secret" .Values.externalDb.superUserPasswordSecret.namespace .Values.externalDb.superUserPasswordSecret.name }}
  {{- $dbSuperUserPassword = index $secret.data .Values.externalDb.superUserPasswordSecret.key | b64dec }}
{{- end }}
{{- if .Values.unleashDb.enabled }}
  {{- $dbUser = .Values.unleashDb.auth.username }}
  {{- $dbUserPassword = .Values.unleashDb.auth.password }}
  {{- $dbSuperUser = "postgres" }}
  {{- $dbSuperUserPassword = .Values.unleashDb.auth.postgresPassword }}
{{- end }}
  UNLEASH_DATABASE_SUPERUSER: {{ $dbSuperUser }}
  UNLEASH_DATABASE_SUPERUSER_PASSWORD: {{ $dbSuperUserPassword | quote }}
  UNLEASH_DATABASE_USER:  {{ $dbUser }}
  UNLEASH_DATABASE_USER_PASSWORD: {{ $dbUserPassword | quote }}
{{- if not .Release.IsUpgrade }}
  UNLEASH_API_TOKEN: ""
  UNLEASH_ADMIN_PASSWORD: {{ randAlphaNum 20 }}
{{- else }}
  {{- $fullName := include "unleash.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
  UNLEASH_API_TOKEN: {{ $secret.data.UNLEASH_API_TOKEN | b64dec | quote }}
  UNLEASH_ADMIN_PASSWORD: {{ $secret.data.UNLEASH_ADMIN_PASSWORD | b64dec | quote }}
{{- end }}
