apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-aion
spec:
  capacity:
    storage: {{ .Values.efs.aion.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.aion.volumeHandle }}
    volumeAttributes:
      encryptInTransit: "true"
