apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-metabase
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-metabase
  resources:
    requests:
      storage: {{ .Values.efs.metabase.volumeSize }}
