apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aion.fullname" . }}
  labels:
    {{- include "aion.labels" . | nindent 4 }}
data:
  AION_REGISTRATION_DROP_VIEWS: "false"
  AION_REGISTRATION_FORCE: "false"  
  AION_DATABASE_SSLMODE: {{ .Values.databaseSSLMode | quote }}
  AION_REPORT_DATABASE_SSLMODE: {{ .Values.reportDatabaseSSLMode | quote }}
  AION_REPORTS_STATEMENT_TIMEOUT: {{ .Values.reportsStatementTimeout | quote }}
  DASHBOARD_EXCLUSIONS: "-"
  DASHBOARD_REDIRECT_URL: "{{ .Values.global.faros.apiUri }}/metabase/dynamic-dashboard"
  AION_PORT: {{ .Values.service.targetPort | quote }}
  FAROS_NODE_OPTIONS: {{ include "faros-ai.farosNodeOptions" . | quote }}
  FEED_TYPES: ""
  GENERIC_DEFAULT_FLOWS: "false"
  GRAPHQL_MAX_PAGE_SIZE: "1000"
  GRAPHQL_V2_PAGINATOR: "keyset"
  METABASE_STATEMENT_TIMEOUT: {{ .Values.metabaseStatementTimeout | quote }}
  TASK_AUDITOR_ENABLE: "false"
  TASK_EXECUTOR_RUN_FREQUENCY: "8 hours"
  TASK_EXECUTOR_SCHEDULE_PATTERN: "*/5 * * * *"
  TASK_MONITOR_RUN_TIMEOUT: "6 hours"
  TASK_MONITOR_SCHEDULE_PATTERN: "*/5 * * * *"
  TASK_SYNCER_SCHEDULE_PATTERN: "*/15 * * * *"
  LOG_LEVEL: "debug"
  NODE_ENV: "production"
