apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aion.fullname" . }}
  labels:
    {{- include "aion.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $dbHost := .Values.externalDb.host }}
  {{- $dbPort := .Values.externalDb.port }}
  {{- $dbName := .Values.externalDb.database }}
  {{- $dbUsername := .Values.externalDb.username }}
  {{- $dbPassword := .Values.externalDb.password }}
  {{- if .Values.aionDb.enabled }}
    {{- $dbHost = printf "%s-%s.%s.svc" .Release.Name .Values.dbName .Release.Namespace }}
    {{- $dbPort = .Values.global.postgresql.service.ports.postgresql }}
    {{- $dbName = .Values.aionDb.auth.database }}
    {{- $dbUsername = .Values.aionDb.auth.username }}
    {{- $dbPassword = .Values.aionDb.auth.password }}
  {{- end }}
  AION_DATABASE_URL: "postgres://{{ $dbUsername }}:{{ $dbPassword }}@{{ $dbHost }}:{{ $dbPort }}/{{ $dbName }}"
  METABASE_CONTROL_USER: {{ .Values.global.metabase.controlUser }}
  METABASE_USER: {{ .Values.global.metabase.user }}
{{- if not .Release.IsUpgrade }}
  METABASE_PASSWORD: {{ randAlphaNum 64 | quote }}
  METABASE_CONTROL_USER_PASSWORD: {{ randAlphaNum 64 | quote }}
{{- else }}
  {{- $fullName := include "aion.fullname" . }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $fullName }}
  METABASE_PASSWORD: {{ $secret.data.METABASE_PASSWORD | b64dec | quote }}
  METABASE_CONTROL_USER_PASSWORD: {{ $secret.data.METABASE_CONTROL_USER_PASSWORD | b64dec | quote }}
{{- end }}
{{- if and .Values.global.datadog.apiKey .Values.global.datadog.appKey }}
  DD_API_KEY: {{ .Values.global.datadog.apiKey | quote }}
  DD_APP_KEY: {{ .Values.global.datadog.appKey | quote }}
  DD_URL: {{ .Values.global.datadog.url | quote }}
{{- end }}
